cart/urls.py
from django.urls import re_path, path
from . import views

urlpatterns = [
    re_path(r'^$', views.show_cart, name='show_cart'),
]

catalog/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.index, name='catalog_home'),
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category, name='catalog_category'),
    re_path(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, name='catalog_product'),
]

ecomstore/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from preview import views
from utils.ssl import ssl_handler

urlpatterns = [
    path('admin/', admin.site.urls, ssl_handler()),
    re_path(r'^catalog/$', views.home, ssl_handler(), name='homalog'),
    re_path(r'^', include('catalog.urls'), ssl_handler()),
    re_path(r'^cart/', include('cart.urls'), ssl_handler()),
    re_path(r'^checkout/', include('checkout.urls'), ssl_handler()),
    re_path(r'^api/v1/', include('mpesa_api.urls'), ssl_handler()),
    re_path(r'^myaccounts/', include('accounts.urls'), ssl_handler()),
]
handler404 = 'ecomstore.views.file_not_found_404'

catalog/models.py
from django.db import models
from django.urls import reverse
# from . import views

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords", max_length=255, help_text='Comma-delimited set ofSEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255, help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog_category', args=[str(self.slug)])

    """def get_absolute_url(self):
        return reverse('catalog_category', {'category_slug': self.slug})"""


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, help_text='Unique value for product page URL, created from name.')
    brand = models.CharField(max_length=50)
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    old_price = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0.00)
    image = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    quantity = models.IntegerField()
    description = models.TextField()
    meta_keywords = models.CharField(max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255, help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog_product', args=[str(self.slug)])

    """def get_absolute_url(self):
        return reverse('catalog_product', (), {'product_slug': self.slug})"""

    @property
    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

catalog/forms.py
from django import forms
from .models import Product


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero.')
        return self.cleaned_data['price']


class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size': '2', 'value': '1', 'class': 'quantity',
                                                                'max_length': '5'}),
                                  error_messages={'Invalid': 'Please enter a valid quantity'}, min_value=1)
    product_slug = forms.CharField(widget=forms.HiddenInput())

    # override the default __init__ so we can set the request
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    # Custom validation to check for cookies
    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
        return self.cleaned_data

catalog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from django.template import RequestContext
from django.urls import reverse
from cart import cart
from django.http import HttpResponseRedirect
from .forms import ProductAddToCartForm
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request, template_name="catalog/index.html"):
    page_title = 'Ezinet Mall'
    context = {
        'page_title': page_title,
    }
    # context2 = RequestContext(request, context)
    return render(request, template_name, locals(), RequestContext(request))


def show_category(request, category_slug, template_name="catalog/category.html"):
    c = get_object_or_404(Category, slug=category_slug)
    products = c.product_set.all()
    page_title = c.name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description
    context = {
        'products': products,
        'page_title': page_title,
        'meta_keywords': meta_keywords,
        'meta_description': meta_description,
    }
    # context2 = RequestContext(request, context)
    return render(request, template_name, locals(), RequestContext(request))


@csrf_exempt
def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.filter(is_active=True)
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    context = {
        'categories': categories,
        'page_title': page_title,
        'meta_keywords': meta_keywords,
        'meta_description': meta_description,
    }
    # need to evaluate the HTTP method
    if request.method == 'POST':
        # add to cart....create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        # check if posted data is valid
        if form.is_valid():
            # add to cart and redirect to cart page
            cart.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = reverse('show_cart')
            return HttpResponseRedirect(url)
    else:
        # it's a get, create the unbound form. Note a request as a kwarg
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set the test cookie on our first get request
    request.session.set_test_cookie()
    return render(request, template_name, locals(), RequestContext(request))

templates/catalog/category.html
{% extends "catalog.html" %}

{% block content %}
    <h1>{{ c.name }}</h1>
    {{ c.description }}
    <br /><br />
    {% for p in products %}
    <div class="product_thumbnail">
        <a href="{{ p.get_absolute_url }}">
            <img src="{{ MEDIA_URL }}images/products/thumbnail/{{ p.image }}" alt="{{ p.name }}" class="bn" />
            <br />
            {{ p.name }}
        </a>&nbsp;
    </div><div></div>
    {% endfor %}
{% endblock %}

templates/catalog/index.html
{% extends "catalog.html" %}

{% block content %}
    <h1>Welcome to Our Online Mall</h1>
    <p>Note: The site is still Under Development.</p>
    <p>Contact <strong>+254 796 525 626</strong> for any queries.</p>
{% endblock %}

templates/catalog/product.html
{% extends "catalog.html" %}
{% load catalog_filters %}

{% block content %}
    <div class="product_image" style="background-image: url({{ MEDIA_URL }}images/products/main/{{ p.image }});">
        <img src="{{ MEDIA_URL }}images/products/main/{{ p.image }}" alt="{{ p.name }}" class="pimage" />
    </div>
    <div class="pright">
        <h1>{{ p.name }}</h1>
        Brand: <em>{{ p.brand }}</em>
        <br /><br />
        SKU: {{ p.sku }}
        <br />
        In categor{{ categories.count|pluralize:"y,ies" }}:
            {% for c in categories %}
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% if not forloop.last %}, {% endif %}
            {% endfor %}
            <br /><br />
        {% if p.sale_price %}
            Was: <del>{{ p.price|currency }}</del>
            <br />
            Now: {{ p.price|currency }}
        {% else %}
            Price: {{ p.price|currency }}
        {% endif %}
        <br /><br />
        <form method="post" action="." class="cart">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <label for="id_quantity">Quantity:</label>
            {{ form.quantity }}
            {{ form.quantity.errors }}
            {{ form.product_slug }}
            <br />
            <input type="submit" value="Add to Cart" name="submit" alt="Add to Cart" />
        </form>
    </div>
    <br />
    <!--<div class="cb"><br /><br /></div>-->
    <div class="cs">
        <h3>Product Description</h3>
        {{ p.description }}
    </div>
{% endblock %}